// Copyright Alex Jobe

#pragma once

#include "NativeGameplayTags.h"

namespace METGameplayTags
{
	/* Input tags */
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_FireWeapon);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AimDownSights);

	/* Attribute tags */
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Health);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxHealth);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_HealthRegeneration);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Armor);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxArmor);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_ArmorPiercing);

	/* Meta attribute tags */
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_IncomingHealthDamage);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_IncomingArmorDamage);

	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FiringMode_SingleShot);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FiringMode_Automatic);
	
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);

	/* Ability tags */
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_FireWeapon);

	/* Event tags */
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(EventTag_FireCooldown);
}