// Copyright Alex Jobe

#pragma once

#include "NativeGameplayTags.h"

/*
 * Game-specific native gameplay tags
 */
namespace METGameplayTags
{
	/* Input tags */
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_FireWeapon);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AimDownSights);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ReloadWeapon);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_CycleAmmo);

	/* Attribute tags */
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Health);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxHealth);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_HealthRegeneration);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Armor);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxArmor);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_ArmorPiercing);

	/* Meta attribute tags */
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_IncomingHealthDamage);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_IncomingArmorDamage);

	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FiringMode_SingleShot);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FiringMode_Automatic);
	
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);

	/* Ability tags */
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_FireWeapon);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_AimDownSights);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ReloadWeapon);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_CycleAmmo);

	/* Event tags */
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(EventTag_FireCooldown);

	/* Weapon tags */
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Pistol);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Rifle);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Shotgun);

	/* AI state tags */
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AIState_Idle);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AIState_Investigating);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AIState_Attacking);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AIState_Hiding);
}