// Copyright Alex Jobe

#pragma once

#include "NativeGameplayTags.h"

namespace METGameplayTags
{
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_FireWeapon);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AimDownSights);

	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Health);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxHealth);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_HealthRegeneration);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Armor);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxArmor);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_ArmorPenetration);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_IncomingDamage);

	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FiringMode_SingleShot);
	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FiringMode_Automatic);

	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

	METEORIC_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
}